compile1:
	g++ traversal.cpp -I . -o traverse
run1:
	./traverse
memcheck1:
	valgrind ./traverse -s --leak-check=full
compile2:
	g++ reverse.cpp -I . -o reverse
run2:
	./reverse
memcheck2:
	valgrind ./reverse -s --leak-check=full